# Copyright (c) 2007-2013 ARM, Inc.  All rights reserved.
#
# This example is intended to be built with the ARM Compiler armcc

APP = IoT-LiB-Cortex-A9x4-FVP.axf
OPT_LEVEL = 1
OPT_FOR = time
CODE_TYPE = thumb
CPU = Cortex-A9
DEFINES = -DSTANDALONE -DSMP

include common.make
